[build]
  base = "/"
  publish = "frontend/storybook-static/"
  command = "npm run build-storybook"

[template.environment]
  NODE_ENV = "production"  
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"
