apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: tooljet
  template:
    metadata:
      labels:
        component: tooljet
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: container
          image: tooljet/saas:latest
          imagePullPolicy: Always
          args: ["npm", "run", "start:prod"]
          resources:
            limits:
              memory: "3002Mi"
              cpu: "700m"
            requests:
              memory: "3000Mi"
              cpu: "700m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: TOOLJET_SERVER_URL
              value: "https://server.tooljet.io"
            - name: RELEASE_VERSION
              value: 0.7.1
            - name: APM_VENDOR
              value: "sentry"
            - name: SERVER_IP
              value: "3.129.198.40"
            - name: SERVE_CLIENT
              value: "false"
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: optional
                  key: gmapskey
            - name: SENTRY_DNS
              value: "https://bc59bffa656d4b039815cf8527ff7b82@o991527.ingest.sentry.io/5953092"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: server
                  key: host
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: server
                  key: user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: server
                  key: password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: server
                  key: db
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: server
                  key: secret_key_base
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: server
                  key: lockbox_key
            - name: ENCRYPTION_SERVICE_SALT
              valueFrom:
                secretKeyRef:
                  name: server
                  key: secret_key_base
            - name: TOOLJET_HOST
              value: "https://app.tooljet.com"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: username
            - name: SMTP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: address
            - name: SMTP_DOMAIN
              value: "smtp.sendgrid.net"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: password
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: google_client_secret
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: slack_client_id
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: slack_client_secret
            - name: customerIoSiteId
              valueFrom:
                secretKeyRef:
                  name: other
                  key: customerIoSiteId
            - name: FWAPIKey
              valueFrom:
                secretKeyRef:
                  name: other
                  key: FWAPIKey
            - name: customerIoApiKey
              valueFrom:
                secretKeyRef:
                  name: other
                  key: customerIoApiKey
            - name: REDIS_HOST
              value: "tooljet-production-elasticache.nfupg8.ng.0001.use2.cache.amazonaws.com"
            - name: DEPLOYMENT_PLATFORM
              value: "k8s"
            - name: HIDE_ACCOUNT_SETUP_LINK
              value: true
            # Set the env values below for Tooljet Database
            # - name: ENABLE_TOOLJET_DB
            #   value: "true"
            # - name: TOOLJET_DB
            #   value: "tooljet_db"
            # - name: TOOLJET_DB_USER
            #   value: "replace_with_tooljet_db_user"
            # - name: TOOLJET_DB_HOST
            #   value: "replace_with_tooljet_db_host"
            # - name: TOOLJET_DB_PASS
            #   value: "replace_with_tooljet_db_pass"
            # - name: PGRST_HOST
            #   value: "replace_with_postgrest_host"
            # - name: PGRST_JWT_SECRET
            #   value: "replace_jwt_secret_here"
