apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet-server-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: tooljet-server
  template:
    metadata:
      labels:
        component: tooljet-server
    spec:
      containers:
        - name: server-container
          image: tooljet/saas:latest
          imagePullPolicy: Always
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          resources:
            limits:
              memory: "3002Mi"
              cpu: "500m"
            requests:
              memory: "3000Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: RAILS_ENV
              value: "production"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: server
                  key: host  
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: server
                  key: user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: server
                  key: password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: server
                  key: db
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: server
                  key: secret_key_base
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: server
                  key: lockbox_key                  
            - name: ENCRYPTION_SERVICE_SALT
              valueFrom:
                secretKeyRef:
                  name: server
                  key: secret_key_base
            - name: TOOLJET_HOST
              valueFrom:
                secretKeyRef:
                  name: server
                  key: tj_host      
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: username
            - name: SMTP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: address   
            - name: SMTP_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: domain    
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: password      
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: google_client_secret
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: slack_client_id
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sources
                  key: slack_client_secret                        

      imagePullSecrets:
        - name: docker-secret
