name: Tooljet release docker images build

on:
  release: 
    types: [published]

  workflow_dispatch:
    inputs:
      job-to-run:
        description: Enter the job name (tooljet-ee/tooljet-server-ee)
        options: ['tooljet-ee', 'tooljet-server-ee']
        required: true
      image:
        description: 'Enter the latest image tag'
        required: true    

jobs:

  build-tooljet-ee-image:
    runs-on: ubuntu-latest
    if: "${{ github.event.release }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: refs/heads/develop

      - name: Set DOCKER_CLI_EXPERIMENTAL
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/production.Dockerfile
          push: true
          tags: tooljet/tooljet-ee:${{ github.event.release.tag_name }},tooljet/tooljet-ee:latest
          platforms: linux/amd64
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Send Slack Notification
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            message="Job '${{ env.JOB_NAME }}' succeeded! docker tooljet/tooljet-ee:${{ github.event.release.tag_name }}"
          else
            message="Job '${{ env.JOB_NAME }}' failed! docker tooljet/tooljet-ee:${{ github.event.release.tag_name }}"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}                   
